### ISSUE TITLE
phunt-desktop: persist application settings

### ISSUE THREAD

**Issue by jelovac** [112dev/phunt#13]
### Description

Define a data store which will be used to persist application settings between runs.

### Design

Initial idea was to use https://github.com/sindresorhus/electron-store. However, maintainer of that library doesn't provide commonjs support and I don't really want to mess anymore with the ts config and rest of build system at this time just for the sake of this library.

So lets build our own thing..

Application configuration should be stored in a file located in the user APP DATA directory. The path of this directory can be obtained using electron's built in functionality. Check https://www.electronjs.org/docs/latest/api/app#appgetpathname .

During application startup, application will check if configuration file exists and load the configuration. If the config is missing, it will create a default configuration file and start writing to it as the user proceeds using the app.

The general practice is to use either JSON or some file based database like sqlite. At the present time I am leaning more towards sqlite because it is easier to set everything up as we already use it for indexing.

### TODO

- [ ] decide between json and sqlite
- [ ] write logic which will create the configuration file if not exists on app startup
- [ ] write logic which will load the configuration from the configuration file on app startup
- [ ] write data store logic for managing the configuration state and persisting it
