### ISSUE TITLE
Add license checker to CI pipeline

### ISSUE THREAD

**Issue by jelovac** [112dev/phunt#2]
### Description

Add a GitHub Action that automatically checks whether the third-party dependencies listed in package.json are compatible with the project's specified SPDX license.

### TODO

- [ ] evaluate available solutions
- [ ] integrate solution into a custom action
- [ ] call the custom action from the CI pipeline
