### ISSUE TITLE
Add license headers

### ISSUE THREAD

**Issue by jelovac** [112dev/phunt#4]
### Description

Automate the process of checking if the source file contains license headers. In addition, add license headers to existing source files.

### TODO

- [ ] Review existing eslint plugins which can perform license header checking
- [ ] Integrate them with the packages/phunt-eslint-config
- [ ] Add missing license headers
